server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  tomcat:
    use-relative-redirects: true

chesstracker2:
  time-zone: Europe/Berlin

spring:
  application:
    name: chesstracker2
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chesstracker2}
    username: ${SPRING_DATASOURCE_USERNAME:chesstracker2}
    password: ${SPRING_DATASOURCE_PASSWORD:chesstracker2_dev}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chesstracker2}
    username: ${SPRING_DATASOURCE_USERNAME:chesstracker2}
    password: ${SPRING_DATASOURCE_PASSWORD:chesstracker2_dev}
  thymeleaf:
    cache: false

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  thymeleaf:
    cache: true
